### ISSUE TITLE
SERVICE - Install systemd service files properly 

### ISSUE THREAD

**Issue by 72nomada** [OwlH-net/OwlH-Installer#12]
Verify service file installation for both master and node

**Comment by seacom** [comment]
Hi,

there is a problem in the installation during the installation, this are the logs:

> FullCopyFile Error creating destination /etc/systemd/system/ file: open /etc/systemd/system/: is a directory

The problem is that it tries to write the systemd unit on a directory. The easier fix would be to explicit the destination file.

[This](https://github.com/OwlH-net/OwlH-Installer/commit/0fd388ee93932c14a098fc4a61747974a3b97615) may be a patch for this issue.

Another alternative would be to detect when the destination is a direcotry on `FullCopyFile`.

**Comment by pingkrimson** [comment]
also having this issue
![Capture](https://user-images.githubusercontent.com/71897553/94297919-e55ce080-ff2a-11ea-8b82-78e3a56f014b.PNG)

**Comment by 72nomada** [comment]
Hi all, 
Commit done, the problem should be solved. 
you can download new owlhinstaller from repo:
```
centOS - repo.owlh.net/current-centos/owlhinstaller
debian - repo.owlh.net/current-centos/owlhinstaller 
```
